### ISSUE TITLE
scrolling long lists with up/down keys

### ISSUE THREAD

**Issue by jmp909** [typesettin/component.selectfx#6]
Hi,

I have a long country list but it can only take up say 300px height, so needs overflow scrolling.
i tried putting overflow scroll on the element but navigating up & down with the keys does not scroll 
the list.

could you give an example of how this should be set up please if I've missed something?

thanks
J

**Comment by yawetse** [comment]
hi @jmp909 I haven't worked on this project in years, unfortunately I don't have a great answer for you

**Comment by codemonkeynorth** [comment]
@yawetse Hi, I realised that from the commits. Just leaving it here for anybody who wishes to take it on ;)
